repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: clang-format
        args: [-i]
# -   repo: https://github.com/executablebooks/mdformat
#     rev: 0.6.4
#     hooks:
#     -   id: mdformat
#         additional_dependencies: ['mdformat-tables']
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: [--ignore=E501,--ignore=E203]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
    -   id: pydocstyle
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
    -   id: pylint
        args: [--disable=C0301,--disable=E0401]
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
      - id: doc8
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
